### ISSUE TITLE
Back button does not work as expected

### ISSUE THREAD

**Issue by dpriskorn** [ringgaard/sling#10]
It loads the former QID in the URL but the page content does not change accordingly. FF 86.0.1 on windows 10

**Comment by ringgaard** [comment]
I don't have a Windows machine, but I tried this on FF 66.0.1 on Linux, and it seems to work. It uses the [History API](https://developer.mozilla.org/en-US/docs/Web/API/History_API) but as far as I can tell, this should work with FireFox. Does it log any errors to the JS log?

**Comment by dpriskorn** [comment]
Works fine in midori on android
