### ISSUE TITLE
Automated SPARQL construction

### ISSUE THREAD

**Issue by PolKul** [ringgaard/sling#11]
Hello, just wanted to ask if there is any tool available for automatic generation of SPARQL queries from the Caspar parsed frames?  The idea is to be able to formulate a natural language query, then convert it to SPARQL to query the KB.

**Comment by ringgaard** [comment]
The caspar parser produces annotations that are similar to PropBank semantic role labeling. I am not sure these are going to be very useful for your task. In general, it usually doesn't help to use intermediate linguistic annotations in the era of deep learning. It is often better to go with an end-to-end learning approach. However, you will need training data for your task, so finding a way to get "cheap" training data is probably going to make a bigger different than an existing classifier trained on 1M words of old news with very few questions.
