### ISSUE TITLE
version `GLIBC_2.27' not found

### ISSUE THREAD

**Issue by mlw67** [ringgaard/sling#12]
\>>> import sling  
return ImportError: /lib64/libc.so.6: version `GLIBC_2.27' not found.
It looks like sling-3.0.0-py3-none-linux_x86_64.whl was built on an Ubuntu 18.04 machine.  Could you please compile it again on an Ubuntu 16.04 machine and redeployed it? thank you very much.

**Comment by ringgaard** [comment]
I don't have any Ubuntu 16.04 machines anymore and I haven't figured out a way to get gcc to build binaries that are compatible with older versions of Ubuntu.

**Comment by mlw67** [comment]
Okay, thank you.
