### ISSUE TITLE
sling fuse_items

### ISSUE THREAD

**Issue by foolfun** [ringgaard/sling#4]
![image](https://user-images.githubusercontent.com/35558298/98913068-db566780-2501-11eb-8c00-a5d4cedc52c6.png)
When I ran the command of "sling fuse_items"  I met this problem.

**Comment by ringgaard** [comment]
This issue have been fixed by [this](https://github.com/ringgaard/sling/commit/8e95d11befe44fade0a43313e69a43cda9d0a499) commit.
