### ISSUE TITLE
Missing screenwriter of?

### ISSUE THREAD

**Issue by dpriskorn** [ringgaard/sling#6]
https://ringgaard.com/kb/Q1368300
has director of but not screenwriter of. Why not? Seems relevant.
It is seen in the graph below:
![2021-03-08-003215_1366x768_scrot](https://user-images.githubusercontent.com/68460690/110259345-75f21f00-7fa7-11eb-99e0-9cb6cdbc20e1.png)
(I got this output by browsing the graph and choosing incoming and clicking Peter Farrelly and then screenwriter.)

**Comment by ringgaard** [comment]
Only a few properties are inverted. I have added screenwriter to this list:

https://github.com/ringgaard/sling/blob/master/data/wiki/recon.sling#L14

After the nightly run you should be able to see this in the knowledge base on ringgaard.com.

**Comment by dpriskorn** [comment]
fixed in https://github.com/ringgaard/sling/commit/21ab3ad113b2b83f16f33188f01b7b98ee884bbd#diff-bbf81089c059056797548a4c5e5f5b4247da3399ed89ee736aa7bc97750e934a

**Comment by anders-sandholm** [comment]
@ringgaard you're fast!
