### ISSUE TITLE
Search for aliases are impossible

### ISSUE THREAD

**Issue by dpriskorn** [ringgaard/sling#8]
Could they be included?
If not what is the motivation for exclusion?

**Comment by ringgaard** [comment]
Aliases are not excluded, so you should be able to search for these. The demo only uses the English aliases. The alias pipeline not only uses labels and aliases from Wikidata. It also includes a number of name-like properties for the items. From Wikipedia titles, redirects, disambiguations, anchors, and a name fields from infoboxes are included. Foreign labels and aliases are also included but only if there are support from other sources, e.g. a French alias would be included if the English Wikipedia has an anchor for it.

Do you have any examples of missing aliases I can test on?

**Comment by dpriskorn** [comment]
I'll try testing 😃

**Comment by dpriskorn** [comment]
Seems fine. Will reopen if I find any not working.
